package com.jdbc.callingstoredprocedure;
import java.sql.* ;

import com.jdbc.crudoperations.DatabaseConnection;


public class AutoGeneratedKeysExample {

	public static int insertStudentAndGetId(String name, String email, int age, String grade) {
		String sql = "INSERT INTO students (name, email, age, grade) VALUES (?, ?, ?, ?)";

		try (Connection conn = DatabaseConnection.getConnection();
		PreparedStatement pstmt = conn.prepareStatement(sql,
		Statement.RETURN_GENERATED_KEYS)) {

		pstmt.setString(1, name);
		pstmt.setString(2, email);
		pstmt.setInt(3, age);
		pstmt.setString(4, grade);

		int affectedRows = pstmt.executeUpdate();

		if (affectedRows > 0) {
		ResultSet generatedKeys = pstmt.getGeneratedKeys();

		if (generatedKeys.next()) {
		int newId = generatedKeys.getInt(1);
		System.out.println("New student ID: " + newId);
		return newId;
		}
		}

		} catch (SQLException e) {
		e.printStackTrace();
		}

		return -1; // Failed
		}

		public static void main(String[] args) {
		int newId = insertStudentAndGetId("Test Student", "test@email.com", 20, "A");
		System.out.println("Inserted student with ID: " + newId);
		}
}
